apidata:
  # image: xnlogic/api-data
  build: api-data/
datomicfree:
  # image: xnlogic/datomic-free
  build: datomic-free/
  volumes_from:
    - apidata
apidev:
  image: busybox
  links:
    - datomicfree:datomic
  command: tail -f /dev/null
auth:
  image: busybox
  command: tail -f /dev/null
nginx:
  build: nginx
  links:
    - apidev:api
    - auth:auth
  ports:
    - 80:80
  

  #api-dev:
  #  build: .
  #  volumes_from:
  #    - api-data
  #  links:
  #    - datomic-free:datomic
  #auth:
  #  build: auth/
  #  volumes_from:
  #    - api-data
